[package]
name = "format"
version = "0.1.0"
authors = ["bingryan <bingryan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.61"
serde = "1.0.120"

anyhow = "1.0.36"
