[package]
name = "json"
version = "0.1.0"
authors = ["bingryan <bingryan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
path = "src/main.rs"
name = "json"

[dependencies]
format = { path = "../../format" }

clap = "2.33.3"