[package]
name = "common"
version = "0.1.0"
authors = ["bingryan <bingryan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# log
log = "0.4.11"
env_logger = "0.8.2"
yansi = "0.5"
chrono = "0.4.19"
