[package]
name = "jtime"
version = "0.1.0"
authors = ["bingryan <bingryan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "jtime"

[dependencies]
serde_json = "1.0.61"
serde = "1.0.120"
chrono = "0.4"


anyhow = "1.0.36"
format = { path = "../../module/format" }
app = {path = "../../module/app"}
common = {path = "../../module/common"}
input = {path = "../../module/input"}


clap = "2.33.3"
log = "0.4.11"
